# Generated by Django 5.1.6 on 2025-03-17 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_class',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
