# Generated by Django 5.1.6 on 2025-03-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0002_task_class_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_class',
            name='date',
        ),
    ]
