# Generated by Django 5.1.6 on 2025-04-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0003_remove_task_class_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themepicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_it_black', models.BooleanField()),
            ],
        ),
    ]
