# Generated by Django 5.1.6 on 2025-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo', '0004_themepicker'),
    ]

    operations = [
        migrations.AddField(
            model_name='themepicker',
            name='tag',
            field=models.CharField(default='tag', max_length=5),
        ),
    ]
